document.addEventListener("DOMContentLoaded", () => {
  const page = document.getElementById("page-categories"); if (!page) return;
  let categories=[], products=[], currentEditId=null, pendingDeleteId=null;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const tbody=page.querySelector(".categories_table tbody"), modal=page.querySelector(".category_modal"), warning=page.querySelector(".warning_modal"), input=modal.querySelector(".form_category_modal input"), title=modal.querySelector("h1");

  async function loadCategories(){tbody.innerHTML='<tr><td colspan="6" class="categories_empty">جاري التحميل...</td></tr>';try{const [cr,pr]=await Promise.all([apiFetch("/menu/categories"),apiFetch("/menu/products")]);if(!cr.ok)throw Error("categories");categories=await cr.json();products=pr.ok?await pr.json():[];categories=categories.map(c=>{const list=products.filter(p=>Number(p.cat_id)===Number(c.id));return{...c,products:list,items_count:list.length,available_count:list.filter(p=>p.is_available).length};});summary();filter();}catch(e){console.error(e);tbody.innerHTML='<tr><td colspan="6" class="categories_empty is_error">تعذر تحميل التصنيفات</td></tr>';}}
  function summary(){const active=categories.filter(c=>c.is_active).length,set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v;};set("categoriesTotalCount",categories.length.toLocaleString("ar-EG"));set("categoriesProductsCount",`${products.length.toLocaleString("ar-EG")} صنف`);set("categoriesActiveCount",active.toLocaleString("ar-EG"));set("categoriesPausedCount",(categories.length-active).toLocaleString("ar-EG"));set("categoriesEmptyCount",categories.filter(c=>!c.items_count).length.toLocaleString("ar-EG"));}
  function filter(){const q=document.getElementById("categoriesSearch").value.trim().toLowerCase(),status=document.getElementById("categoriesStatusFilter").value,sort=document.getElementById("categoriesSort").value;const rows=categories.filter(c=>(!q||c.cat_name.toLowerCase().includes(q))&&(status==="all"||(status==="active"?c.is_active:!c.is_active)));rows.sort((a,b)=>sort==="items_desc"?b.items_count-a.items_count:sort==="items_asc"?a.items_count-b.items_count:a.cat_name.localeCompare(b.cat_name,"ar"));render(rows);}
  function render(rows){document.getElementById("categoriesTableCaption").textContent=`عرض ${rows.length.toLocaleString("ar-EG")} من ${categories.length.toLocaleString("ar-EG")} تصنيف`;if(!rows.length){tbody.innerHTML='<tr><td colspan="6" class="categories_empty">لا توجد تصنيفات مطابقة</td></tr>';return;}tbody.innerHTML=rows.map(c=>`<tr><td><button class="category_name_btn" data-view="${c.id}"><strong>${esc(c.cat_name)}</strong><small>${c.items_count?"عرض الأصناف":"تصنيف فارغ"}</small></button></td><td>${c.items_count.toLocaleString("ar-EG")}</td><td><span class="category_count available">${c.available_count.toLocaleString("ar-EG")}</span></td><td><span class="category_count paused">${(c.items_count-c.available_count).toLocaleString("ar-EG")}</span></td><td class="switch_td"><span class="category_status ${c.is_active?"is_active":"is_paused"}">${c.is_active?"نشط":"موقوف"}</span><div class="switch ${c.is_active?"":"active"}" data-toggle="${c.id}"><div class="circle"></div></div></td><td><div class="event_icons"><img src="/assets/delete.png" data-delete="${c.id}" class="delete_icon"><img src="/assets/Edit_light.png" data-edit="${c.id}" class="edit_icon"></div></td></tr>`).join("");}
  async function toggle(id){const r=await apiFetch(`/menu/categories/${id}/toggle`,{method:"PATCH",hideLoader:true});if(!r.ok)return alert("تعذر تغيير الحالة");const u=await r.json(),c=categories.find(x=>Number(x.id)===Number(id));if(c)c.is_active=u.is_active;summary();filter();}
  function drawer(id){const c=categories.find(x=>Number(x.id)===Number(id));if(!c)return;document.getElementById("categoryDrawerTitle").textContent=c.cat_name;document.getElementById("categoryDrawerSummary").innerHTML=`<div class="category_drawer_stats"><div><span>إجمالي</span><strong>${c.items_count}</strong></div><div><span>متاح</span><strong>${c.available_count}</strong></div><div><span>موقوف</span><strong>${c.items_count-c.available_count}</strong></div></div>`;document.getElementById("categoryDrawerProducts").innerHTML=c.products.length?c.products.map(p=>`<div><span><i class="${p.is_available?"active":"paused"}"></i>${esc(p.product_name)}</span><strong>${p.is_available?"متاح":"موقوف"}</strong></div>`).join(""):'<div class="categories_empty">لا توجد أصناف</div>';const d=document.getElementById("categoryProductsDrawer");d.classList.add("is_open");d.setAttribute("aria-hidden","false");}
  function closeDrawer(){const d=document.getElementById("categoryProductsDrawer");d.classList.remove("is_open");d.setAttribute("aria-hidden","true");}
  page.addEventListener("click",e=>{const v=e.target.closest("[data-view]");if(v)return drawer(v.dataset.view);const t=e.target.closest("[data-toggle]");if(t)return toggle(t.dataset.toggle);const ed=e.target.closest("[data-edit]");if(ed)return openEdit(ed.dataset.edit);const del=e.target.closest("[data-delete]");if(del){pendingDeleteId=del.dataset.delete;warning.style.display="flex";}});
  page.querySelector(".categories_header .add_category_btn").onclick=()=>{currentEditId=null;title.textContent="أضف تصنيف جديد";input.value="";clearFieldState(input);modal.style.display="flex";};
  function openEdit(id){currentEditId=id;title.textContent="تعديل التصنيف";input.value=categories.find(c=>Number(c.id)===Number(id))?.cat_name||"";clearFieldState(input);modal.style.display="flex";}function closeModal(){modal.style.display="none";currentEditId=null;clearFieldState(input);}
  input.oninput=()=>validateField(input,"categoryName");modal.querySelector(".add_category_btn").onclick=async()=>{if(!validateField(input,"categoryName"))return;const r=await apiFetch(currentEditId?`/menu/categories/${currentEditId}`:"/menu/categories",{method:currentEditId?"PATCH":"POST",body:JSON.stringify({cat_name:input.value.trim()})});if(r.ok){closeModal();loadCategories();}else alert("تعذر حفظ التصنيف");};modal.querySelector(".cancel_category_btn").onclick=closeModal;modal.querySelector(".category_exit img").onclick=closeModal;
  warning.querySelector(".warning_exit img").onclick=()=>warning.style.display="none";warning.querySelector(".confirm_btn").onclick=async()=>{if(!pendingDeleteId)return;const c=categories.find(x=>Number(x.id)===Number(pendingDeleteId));if(c?.items_count){warning.style.display="none";return alert("التصنيف يحتوي أصنافًا. أوقفه بدل الحذف للحفاظ على بيانات الطلبات.");}const r=await apiFetch(`/menu/categories/${pendingDeleteId}`,{method:"DELETE"});if(r.ok){warning.style.display="none";loadCategories();}else alert("تعذر حذف التصنيف");};
  document.getElementById("categoriesSearch").oninput=filter;document.getElementById("categoriesStatusFilter").onchange=filter;document.getElementById("categoriesSort").onchange=filter;document.getElementById("categoriesResetFilters").onclick=()=>{document.getElementById("categoriesSearch").value="";document.getElementById("categoriesStatusFilter").value="all";document.getElementById("categoriesSort").value="name";filter();};document.getElementById("closeCategoryDrawer").onclick=closeDrawer;page.querySelector(".category_drawer_backdrop").onclick=closeDrawer;window.refreshCategoriesPage=loadCategories;loadCategories();
});
