"""db_updates

Revision ID: 0c2a7edc1a91
Revises: d400257c166f
Create Date: 2026-04-20 19:36:47.958043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2a7edc1a91'
down_revision: Union[str, Sequence[str], None] = 'd400257c166f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    op.drop_column('orders', 'order_seq')
    op.drop_constraint(op.f('products_product_name_key'), 'products', type_='unique')
    op.create_unique_constraint('uq_product_name_cat_id', 'products', ['product_name', 'cat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_name_cat_id', 'products', type_='unique')
    op.create_unique_constraint(op.f('products_product_name_key'), 'products', ['product_name'], postgresql_nulls_not_distinct=False)
    op.add_column('orders', sa.Column('order_seq', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    # ### end Alembic commands ###
