"""add order modification history

Revision ID: 19c7dd1df5fb
Revises: a121c91fa563
Create Date: 2026-07-07 04:48:13.710191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '19c7dd1df5fb'
down_revision: Union[str, Sequence[str], None] = 'a121c91fa563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_modification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_modification_history_id'), 'order_modification_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_modification_history_order_id'), 'order_modification_history', ['order_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_modification_history_order_id'), table_name='order_modification_history')
    op.drop_index(op.f('ix_order_modification_history_id'), table_name='order_modification_history')
    op.drop_table('order_modification_history')
    # ### end Alembic commands ###
