"""add_soft_delete_columns_fixed_v2

Revision ID: 2c39ca918760
Revises: 47aa4a34ee96
Create Date: 2026-05-09 15:05:11.489693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c39ca918760'
down_revision: Union[str, Sequence[str], None] = '47aa4a34ee96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use server_default to avoid NOT NULL violations on existing rows
    op.add_column('app_settings', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('app_settings', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('customer_addresses', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('customer_addresses', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('customers', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    op.add_column('offers', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('offers', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # Note: Enum changes might be complex depending on DB, but keeping them as sa.Enum for generic compatibility
    op.add_column('order_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    op.add_column('order_status_history', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('order_status_history', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    
    op.add_column('variants', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('variants', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    
    # Clean up server defaults if you don't want them persistent (optional, but keeping for safety)
    # op.alter_column('categories', 'is_deleted', server_default=None)
    # ...


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'updated_at')
    op.drop_column('variants', 'is_deleted')
    op.drop_column('users', 'is_deleted')
    op.drop_column('products', 'is_deleted')
    op.alter_column('outbox_events', 'status',
               existing_type=app.core.database.DbEnum('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED'),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED', name='outboxeventstatus'),
               existing_nullable=False)
    op.drop_column('orders', 'is_deleted')
    op.drop_column('order_status_history', 'updated_at')
    op.drop_column('order_status_history', 'is_deleted')
    op.drop_column('order_items', 'updated_at')
    op.drop_column('order_items', 'is_deleted')
    op.alter_column('offers', 'discount_type',
               existing_type=app.core.database.DbEnum('PERCENTAGE', 'FIXED', 'BUY_ONE_GET_ONE'),
               type_=postgresql.ENUM('PERCENTAGE', 'FIXED', 'BUY_ONE_GET_ONE', 'SEASONAL_DISCOUNT', 'PROMO_CODE', 'BULK_DISCOUNT', name='discounttype'),
               existing_nullable=False)
    op.drop_column('offers', 'updated_at')
    op.drop_column('offers', 'is_deleted')
    op.drop_column('customers', 'updated_at')
    op.drop_column('customers', 'is_deleted')
    op.drop_column('customer_addresses', 'updated_at')
    op.drop_column('customer_addresses', 'is_deleted')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'is_deleted')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'is_deleted')
    op.drop_column('app_settings', 'updated_at')
    op.drop_column('app_settings', 'is_deleted')
    # ### end Alembic commands ###
