"""Add active_devices table

Revision ID: 39cca0e95f22
Revises: 602664a735cd
Create Date: 2026-05-06 01:02:50.775157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39cca0e95f22'
down_revision: Union[str, Sequence[str], None] = '602664a735cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('active_devices',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox_events', 'status',
               existing_type=app.core.database.DbEnum('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED'),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED', name='outboxeventstatus'),
               existing_nullable=False)
    op.alter_column('offers', 'discount_type',
               existing_type=app.core.database.DbEnum('PERCENTAGE', 'FIXED', 'BUY_ONE_GET_ONE'),
               type_=postgresql.ENUM('PERCENTAGE', 'FIXED', 'BUY_ONE_GET_ONE', 'SEASONAL_DISCOUNT', 'PROMO_CODE', 'BULK_DISCOUNT', name='discounttype'),
               existing_nullable=False)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_full_name'), 'comments', ['full_name'], unique=False)
    op.create_index(op.f('idx_comment_stars'), 'comments', ['stars'], unique=False)
    op.create_index(op.f('idx_comment_created'), 'comments', ['created_at'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('app_settings_pkey'))
    )
    op.drop_table('active_devices')
    # ### end Alembic commands ###
