"""add_full_name_to_users

Revision ID: 67725a851965
Revises: 6ac23eb1f0f0
Create Date: 2026-04-14 21:18:55.672021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67725a851965'
down_revision: Union[str, Sequence[str], None] = '6ac23eb1f0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_offer_active'), table_name='offers')
    op.drop_index(op.f('idx_offer_valid_dates'), table_name='offers')
    op.drop_index(op.f('idx_order_customer_phone'), table_name='orders')
    op.drop_index(op.f('idx_order_date_status'), table_name='orders')
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.create_index(op.f('idx_order_date_status'), 'orders', ['order_date', 'order_status'], unique=False)
    op.create_index(op.f('idx_order_customer_phone'), 'orders', ['customer_phone'], unique=False)
    op.create_index(op.f('idx_offer_valid_dates'), 'offers', ['valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('idx_offer_active'), 'offers', ['is_active'], unique=False)
    # ### end Alembic commands ###
