"""drop addons

Revision ID: 7b452148557f
Revises: 0c2a7edc1a91
Create Date: 2026-04-20 19:47:46.729123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b452148557f'
down_revision: Union[str, Sequence[str], None] = '0c2a7edc1a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('addon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('addon_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('addons_pkey')),
    sa.UniqueConstraint('addon_name', name=op.f('addons_addon_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
