"""create_missing_tables

Revision ID: 9ae20d01ff00
Revises: 821024f71ca7
Create Date: 2026-04-14 20:42:14.430995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae20d01ff00'
down_revision: Union[str, Sequence[str], None] = '821024f71ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_table('customer_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_id'), 'customer_addresses', ['id'], unique=False)
    op.create_table('offer_usages',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(length=255), nullable=True),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.offer_id'], ),
    sa.PrimaryKeyConstraint('usage_id'),
    sa.UniqueConstraint('offer_id', 'customer_phone', name='uq_offer_customer_usage')
    )
    op.create_index('idx_offer_customer', 'offer_usages', ['offer_id', 'customer_phone'], unique=False)
    op.create_index(op.f('ix_offer_usages_cashier_id'), 'offer_usages', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_offer_usages_customer_phone'), 'offer_usages', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_offer_usages_offer_id'), 'offer_usages', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_usages_usage_id'), 'offer_usages', ['usage_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('order_seq', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_person_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Enum('HALL', 'TAKEAWAY', 'DELIVERY', 'ONLINE', name='ordertype'), nullable=False),
    sa.Column('order_status', sa.Enum('NEW', 'CONFIRMED', 'COMPLETED', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('order_source', sa.Enum('CASHIER', 'ONLINE', name='ordersource'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_addresses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'order_date', name='uq_idempotency_per_day')
    )
    op.create_index('idx_order_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_number_date', 'orders', ['order_number', 'order_date'], unique=True)
    op.create_index('idx_order_source', 'orders', ['order_source'], unique=False)
    op.create_index('idx_order_status', 'orders', ['order_status'], unique=False)
    op.create_index('idx_order_type', 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'confirmed', 'completed', 'delivered', 'cancelled', name='order_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.drop_index(op.f('ix_addons_id'), table_name='addons')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.add_column('offers', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('offers', sa.Column('min_quantity', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('max_quantity', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('current_usage', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('offers', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('offers', 'min_order_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('offers', 'max_discount_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('offers', 'max_discount_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('offers', 'min_order_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('offers', 'version')
    op.drop_column('offers', 'current_usage')
    op.drop_column('offers', 'max_quantity')
    op.drop_column('offers', 'min_quantity')
    op.drop_column('offers', 'display_name')
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_addons_id'), 'addons', ['id'], unique=False)
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_order_type', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_source', table_name='orders')
    op.drop_index('idx_order_number_date', table_name='orders')
    op.drop_index('idx_order_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_offer_usages_usage_id'), table_name='offer_usages')
    op.drop_index(op.f('ix_offer_usages_offer_id'), table_name='offer_usages')
    op.drop_index(op.f('ix_offer_usages_customer_phone'), table_name='offer_usages')
    op.drop_index(op.f('ix_offer_usages_cashier_id'), table_name='offer_usages')
    op.drop_index('idx_offer_customer', table_name='offer_usages')
    op.drop_table('offer_usages')
    op.drop_index(op.f('ix_customer_addresses_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
