"""add_performance_indexes

Revision ID: c2e60dde8bd5
Revises: 67725a851965
Create Date: 2026-04-18 21:22:35.882827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e60dde8bd5'
down_revision: Union[str, Sequence[str], None] = '67725a851965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('idx_order_date_source', 'orders', ['order_date', 'order_source'], unique=False)
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_index(op.f('ix_orders_created_by_user_id'), 'orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_delivery_person_id'), 'orders', ['delivery_person_id'], unique=False)
    op.create_index(op.f('ix_products_cat_id'), 'products', ['cat_id'], unique=False)
    op.create_index(op.f('ix_variants_product_id'), 'variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_product_id'), table_name='variants')
    op.drop_index(op.f('ix_products_cat_id'), table_name='products')
    op.drop_index(op.f('ix_orders_delivery_person_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_index('idx_order_date_source', table_name='orders')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    # ### end Alembic commands ###
