"""add outbox event

Revision ID: fd6a6d4d5426
Revises: 7b452148557f
Create Date: 2026-05-05 21:34:34.921497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd6a6d4d5426'
down_revision: Union[str, Sequence[str], None] = '7b452148557f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create Enum type safely for PostgreSQL
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outbox_event_status') THEN CREATE TYPE outbox_event_status AS ENUM ('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED'); END IF; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'FAILED', 'COMPLETED', name='outbox_event_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_status', 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_id'), 'outbox_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_id'), table_name='outbox_events')
    op.drop_index('idx_outbox_status', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
